-- ============================================================
-- ZUBERI CUP — Supabase Schema
-- Run this in your Supabase SQL Editor (Project → SQL Editor → New Query)
-- ============================================================

-- ── MATCHES ──────────────────────────────────────────────────
create table if not exists matches (
  id          bigint generated by default as identity primary key,
  team_a      text    not null default 'Timu A',
  team_b      text    not null default 'Timu B',
  score_a     integer not null default 0,
  score_b     integer not null default 0,
  minute      integer not null default 0,
  status      text    not null default 'upcoming'
                check (status in ('upcoming','live','ft')),
  venue       text    not null default 'Uwanja wa Railway',
  match_date  date    not null default current_date,
  created_at  timestamptz default now()
);

-- ── SCORERS ──────────────────────────────────────────────────
create table if not exists scorers (
  id          bigint generated by default as identity primary key,
  match_id    bigint  not null references matches(id) on delete cascade,
  team_side   text    not null check (team_side in ('A','B')),
  player_name text    not null,
  minute      integer not null,
  created_at  timestamptz default now()
);

-- ── NEWS ─────────────────────────────────────────────────────
create table if not exists news (
  id          bigint generated by default as identity primary key,
  title       text    not null,
  description text,
  image_url   text    default '',
  tag         text    default 'Habari',
  news_date   date    default current_date,
  featured    boolean default false,
  created_at  timestamptz default now()
);

-- ── REGISTRATIONS (Jaza Fomu) ─────────────────────────────────
create table if not exists registrations (
  id          bigint generated by default as identity primary key,
  team_name   text    not null,
  coach_name  text    not null,
  phone       text    not null,
  location    text    default '',
  players_count integer default 11,
  notes       text    default '',
  created_at  timestamptz default now()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
alter table matches       enable row level security;
alter table scorers       enable row level security;
alter table news          enable row level security;
alter table registrations enable row level security;

-- Public can read matches, scorers, news
create policy "public_read_matches"  on matches       for select using (true);
create policy "public_read_scorers"  on scorers       for select using (true);
create policy "public_read_news"     on news          for select using (true);

-- Only service role (server-side API) can write — achieved by NOT adding
-- anon insert/update/delete policies. The server uses the service_role key
-- which bypasses RLS entirely.

-- Registrations: anyone can insert (public form), only service role can read
create policy "public_insert_registrations" on registrations for insert with check (true);

-- ============================================================
-- ENABLE REALTIME
-- ============================================================
alter publication supabase_realtime add table matches;
alter publication supabase_realtime add table scorers;

-- ============================================================
-- SEED DATA — initial matches for testing
-- ============================================================
insert into matches (team_a, team_b, score_a, score_b, minute, status, venue, match_date) values
  ('Afro Boys FC',    'Eagle FC',          2, 1, 67, 'live',     'Uwanja wa Railway', current_date),
  ('Pasua Big Stars', 'Msaranga FC',       1, 1, 45, 'live',     'Uwanja wa Railway', current_date),
  ('Kili Wonders FC', 'Moshi United FC',   0, 0,  0, 'upcoming', 'Uwanja wa Railway', current_date);

insert into scorers (match_id, team_side, player_name, minute) values
  (1, 'A', 'J. Mwangi', 23),
  (1, 'A', 'R. Sanga',  54),
  (1, 'B', 'P. Kilima', 41),
  (2, 'A', 'D. Maro',   12),
  (2, 'B', 'S. Shayo',  33);

insert into news (title, description, image_url, tag, news_date, featured) values
  ('Afro Boys FC achukua Ubingwa wa Mashindano ya Zuberi Cup 2025',
   'Timu ya Afro Boys FC yatinga fainali na kuchukua ubingwa dhidi ya Pasua Big Stars kwenye msimu wa Tano.',
   'https://zubericup.com/washindi.jpg', 'Ubingwa', '2025-09-26', true),
  ('Mgeni Rasmi wa Fainali — Bi. Mwajuma Nasombe',
   'Bi Mwajuma Nasimbe amefika uwanjani kushuhudia fainali.',
   'https://zubericup.com/meya.jpg', 'Fainali', '2025-09-26', false),
  ('Msaranga FC ashika Nafasi ya Tatu',
   'Msaranga FC ameshika nafasi ya Mshindi wa Tatu baada ya Kuwacharaza Kili Wonders FC 2–0.',
   'https://zubericup.com/uwanja.jpg', 'Matokeo', '2025-09-25', false);
